### ISSUE TITLE
Most modules are private

### ISSUE THREAD

**Issue by Zandario** [Aiving/material-colors#1]
Started rewriting a tool I made using material-color-utilities with this and it seems like most of the modules aren't properly exported as public, I haven't checked them all but for me I mainly need to be able to make `Hct`s and `argb`s

**Comment by Aiving** [comment]
I apologize for the delay (I don't often read notifications on github). I will solve this problem today.

**Comment by Aiving** [comment]
I suppose this issue can be closed after the release of 0.1.1.

**Comment by Zandario** [comment]
All good! I understand this is still very new, just wanted to let you know
