### ISSUE TITLE
Document breaking changes

### ISSUE THREAD

**Issue by allan2** [Aiving/material-colors#10]
0.2 has a lot of breaking changes.

Something like *CHANGELOG.md* would be nice to have. I like how [axum's changelog](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md) specifies whether a change is breaking, a fix, or an addition. This could also be included in future release notes.

By the way, thanks for the shoutout in 0.2.1!

**Comment by Aiving** [comment]
closed in e50bb2e

**Comment by allan2** [comment]
That is quite a detailed and history-complete changelog. Kudos :)
