### ISSUE TITLE
Colour match feature

### ISSUE THREAD

**Issue by allan2** [Aiving/material-colors#17]
The [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/) (GitHub pages version) has a colour match feature, where the primary colour is identical to the source colour.

It would be nice if the crate supported this.

For the source `#6750A4`:

Regular:
![theme](https://github.com/Aiving/material-colors/assets/6740989/b118bb3a-0653-4753-993c-611f31d51227)

Colour-matched:
![theme_color_match](https://github.com/Aiving/material-colors/assets/6740989/47bbb3dc-50f0-4daf-97da-25e23098de3d)

**Comment by Aiving** [comment]
The library already has a Color Match feature and it's called SchemeFidelity, isn't it?

**Comment by allan2** [comment]
Ah, I did not know. Is it possible to have this as `ThemeBuilder::color_match`?

**Comment by Aiving** [comment]
Ofc, why not
