### ISSUE TITLE
Set and override theme core colors

### ISSUE THREAD

**Issue by allan2** [Aiving/material-colors#22]
The [Material Theme Builder](https://material-foundation.github.io/material-theme-builder/) allows you to customize.

We currently only support creation by specifying a source colour.

When I first discovered the library, I tried to add a secondary colour incorrectly via `custom_colors`, which is like the *Extended colors* section in the Theme Builder.

It would be nice if we could input a secondary input and have that update the theme. We should at least support the core color overrides in the theme builder, i.e., primary, secondary, tertiary, error, neutral, neutral variant..

Ideally, there is a way to set this at creation.
This could be done after creation with `set_secondary`, `set_tertiary`, etc.

**Comment by Aiving** [comment]
closed in bb48350
