### ISSUE TITLE
quantize: thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by InioX** [Aiving/material-colors#3]
Code:
```rs
// Opening image is cut off

let pixels: Vec<Argb> = img.pixels().fold(vec![], |mut pixels, pixel| {
        // creating ARGB from RGBA
        pixels.push([pixel[3], pixel[0], pixel[1], pixel[2]]);

        pixels
});

let result = QuantizerCelebi.quantize(&pixels, 128, None);
```
Error:
```
thread 'main' has overflowed its stack (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

I first noticed this happening with `QuantizerCelebi`, so I tried only `QuantizerWu` and it is still the same error.

**Comment by Aiving** [comment]
I'll try to fix that.

**Comment by Aiving** [comment]
Could you please provide an image (as a URL or a file; it doesn't matter)? I tried to use the example from the README, and everything seems to be fine.

**Comment by InioX** [comment]
Hi, 

I tried again today and I must have used a wrong image or opened it incorrecly. Anyways, it works now))
